- .gitignore
.DS_Store
.DS_Store?
.Trashes
JIRA: https://wso2.org/jira/browse/REGISTRY-2396
> Adding files to .gitignore

- components/registry/org.wso2.carbon.registry.social.impl/src/test/java/org/wso2/carbon/registry/social/impl/test/activity/ActivityManagerImplTest.java
please revert this after testing ends
> To test methode execution order - this will be removed afterwards

- components/registry/org.wso2.carbon.registry.social.impl/src/test/java/org/wso2/carbon/registry/social/impl/test/activity/ActivityManagerImplTest.java
> To test methode execution order - this will be removed afterwards phase2

- components/registry/org.wso2.carbon.registry.task/src/main/java/org/wso2/carbon/registry/task/internal/RegistryTaskServiceComponent.java
Registered task type registryTasks.
> Fixing public JIRA: https://wso2.org/jira/browse/REGISTRY-2432

- components/registry/org.wso2.carbon.registry.extensions/src/main/java/org/wso2/carbon/registry/extensions/handlers/ZipWSDLMediaTypeHandler.java
- components/registry/org.wso2.carbon.registry.extensions/src/main/java/org/wso2/carbon/registry/extensions/handlers/utils/EndpointUtils.java
- components/registry/org.wso2.carbon.registry.extensions/src/main/java/org/wso2/carbon/registry/extensions/utils/CommonConstants.java
- components/registry/org.wso2.carbon.registry.extensions/src/test/java/org/wso2/carbon/registry/extensions/test/EndpointUtilsTest.java
https://wso2.org/jira/browse/REGISTRY-2460
> Correcting EndpointUtils to display dependent endpoints

- components/registry/org.wso2.carbon.registry.resource/pom.xml
- components/registry/org.wso2.carbon.registry.resource/src/test/java/org.wso2.carbon.registry.resource.test/Registry2395Test.java
https://wso2.org/jira/browse/REGISTRY-2395
> Unit tests for Resource(WSDL/WADL/Schema/Policy) upload path change

- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/SolrConstants.java
- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/indexer/IndexDocumentCreator.java
- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/solr/SolrClient.java
Reverts wso2/carbon-registry#50
> Revert "Enabled multivalued support for property fields"

- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/SolrConstants.java
- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/indexer/IndexDocumentCreator.java
- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/solr/SolrClient.java
- features/content-search/org.wso2.carbon.registry.contentsearch.server.feature/pom.xml
This will fixed the property search issue. multi value in property was not supported. add multi values is supported with this fix
> Fixed Advanced properties search issue and guava lib to search feature

- components/registry/org.wso2.carbon.registry.caching.invalidator/src/main/resources/cache.properties
- components/registry/org.wso2.carbon.registry.common/src/main/java/org/wso2/carbon/registry/common/TermData.java
- components/registry/org.wso2.carbon.registry.extensions/src/main/java/org/wso2/carbon/registry/extensions/handlers/AbstractMediaTypeHandler.java
- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/IndexingConstants.java
- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/internal/IndexingServiceComponent.java
- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/service/ContentBasedSearchService.java
- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/service/SearchResultsBean.java
- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/service/TermsSearchService.java
- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/solr/SolrClient.java
- features/caching-invalidator/org.wso2.carbon.registry.caching.invalidator.server.feature/src/main/resources/conf/cache.properties
Please note: We need to test and verify the functionality before merging.
> Enable term search in registry - phase 01

- components/registry/org.wso2.carbon.registry.relations/src/main/java/org/wso2/carbon/registry/relations/internal/RegistryMgtUIRelationsServiceComponent.java
- components/registry/org.wso2.carbon.registry.relations/src/main/java/org/wso2/carbon/registry/relations/internal/RelationsDataHolder.java
- components/registry/org.wso2.carbon.registry.relations/src/main/java/org/wso2/carbon/registry/relations/services/utils/CommonUtil.java
https://wso2.org/jira/browse/REGISTRY-2567
> Fix for REGISTRY-2567 - singleton data holder within the registry relations

- components/registry/org.wso2.carbon.registry.ws.api/src/main/java/org/wso2/carbon/registry/ws/api/WSRegistry.java
- components/registry/org.wso2.carbon.registry.ws.api/src/main/java/org/wso2/carbon/registry/ws/api/internal/WSDataHolder.java
- components/registry/org.wso2.carbon.registry.ws.api/src/main/java/org/wso2/carbon/registry/ws/api/internal/WSRegistryServiceComponent.java
- components/registry/org.wso2.carbon.registry.ws.api/src/main/java/org/wso2/carbon/registry/ws/api/utils/CommonUtil.java
https://wso2.org/jira/browse/REGISTRY-2571
> Fix for REGISTRY-2571 - singleton data holder within the registry ws/api

- components/registry/org.wso2.carbon.registry.ws.client/src/main/java/org/wso2/carbon/registry/ws/client/internal/WSClientDataHolder.java
- components/registry/org.wso2.carbon.registry.ws.client/src/main/java/org/wso2/carbon/registry/ws/client/internal/WSClientServiceComponent.java
- components/registry/org.wso2.carbon.registry.ws.client/src/main/java/org/wso2/carbon/registry/ws/client/registry/WSRegistryClientUtils.java
- components/registry/org.wso2.carbon.registry.ws.client/src/main/java/org/wso2/carbon/registry/ws/client/registry/WSRegistryServiceClient.java
https://wso2.org/jira/browse/REGISTRY-2572
> Fix for REGISTRY-2572 - singleton data holder within the registry wsclient

- components/registry/org.wso2.carbon.registry.resource/src/main/java/org/wso2/carbon/registry/resource/services/utils/CommonUtil.java
- components/registry/org.wso2.carbon.registry.resource/src/test/java/org.wso2.carbon.registry.resource.test/Registry2395Test.java
https://wso2.org/jira/browse/REGISTRY-2569
> Fix for REGISTRY-2569 - Using clone method to mirror values in original array and adding unit tests

- components/registry/org.wso2.carbon.registry.rest.api/src/main/java/org/wso2/carbon/registry/rest/api/handler/RestApiBasicAuthenticationHandler.java
[1] https://wso2.org/jira/browse/REGISTRY-2717
> fix for REGISTRY-2717

- components/registry/org.wso2.carbon.registry.indexing.ui/pom.xml
- components/registry/org.wso2.carbon.registry.indexing/pom.xml
- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/solr/SolrClient.java
- components/registry/org.wso2.carbon.registry.metadata/pom.xml
- features/content-search/org.wso2.carbon.registry.contentsearch.server.feature/pom.xml
Reverts wso2/carbon-registry#91
> Revert "moving to solr version 5.2.1.wso2v1 from 5.0.0.wso2v1"

- org.wso2.carbon.metadata.server/src/main/java/org/wso2/carbon/metadata/server/dao/MetadataDAO.java
- org.wso2.carbon.metadata.server/src/main/java/org/wso2/carbon/metadata/server/dao/inmemory/InMemoryMetadataDAO.java
- org.wso2.carbon.metadata.server/src/main/java/org/wso2/carbon/metadata/server/dao/jdbc/JDBCMetadataDAO.java
Implementing InMemoryMetaDatDAO
> Carbon metadata

- org.wso2.carbon.metadata.server/src/main/java/org/wso2/carbon/metadata/server/dao/MetadataDAO.java
- org.wso2.carbon.metadata.server/src/main/java/org/wso2/carbon/metadata/server/dao/inmemory/InMemoryMetadataDAO.java
- org.wso2.carbon.metadata.server/src/main/java/org/wso2/carbon/metadata/server/dao/jdbc/JDBCMetadataDAO.java
Change exception types to MetadataStoreException
> Change exception types

- features/registry-task/org.wso2.carbon.registry.task.server.feature/pom.xml
Compatible check to upgrade carbon-commons version
> ESB Carbon Analytics Common Upgrade

- components/registry/org.wso2.carbon.registry.extensions/src/main/java/org/wso2/carbon/registry/extensions/handlers/TaxonomyResourceHandler.java
- components/registry/org.wso2.carbon.registry.extensions/src/main/java/org/wso2/carbon/registry/extensions/services/TaxonomyStorageService.java
- components/registry/org.wso2.carbon.registry.extensions/src/main/java/org/wso2/carbon/registry/extensions/services/Utils.java
- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/IndexingConstants.java
- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/indexer/IndexDocumentCreator.java
- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/solr/SolrClient.java
> Adding taxonomy milestone1

- components/registry/org.wso2.carbon.registry.extensions/src/main/java/org/wso2/carbon/registry/extensions/handlers/RESTServiceMediaTypeHandler.java
- components/registry/org.wso2.carbon.registry.extensions/src/main/java/org/wso2/carbon/registry/extensions/handlers/SOAPServiceMediaTypeHandler.java
- components/registry/org.wso2.carbon.registry.extensions/src/main/java/org/wso2/carbon/registry/extensions/handlers/ServiceMediaTypeHandler.java
- components/registry/org.wso2.carbon.registry.extensions/src/main/java/org/wso2/carbon/registry/extensions/handlers/SwaggerMediaTypeHandler.java
- components/registry/org.wso2.carbon.registry.extensions/src/main/java/org/wso2/carbon/registry/extensions/handlers/WADLMediaTypeHandler.java
- components/registry/org.wso2.carbon.registry.extensions/src/main/java/org/wso2/carbon/registry/extensions/handlers/ZipWSDLMediaTypeHandler.java
- components/registry/org.wso2.carbon.registry.extensions/src/main/java/org/wso2/carbon/registry/extensions/handlers/utils/RESTServiceUtils.java
- components/registry/org.wso2.carbon.registry.extensions/src/main/java/org/wso2/carbon/registry/extensions/handlers/utils/SwaggerProcessor.java
- components/registry/org.wso2.carbon.registry.extensions/src/main/java/org/wso2/carbon/registry/extensions/handlers/utils/WADLProcessor.java
- components/registry/org.wso2.carbon.registry.extensions/src/main/java/org/wso2/carbon/registry/extensions/utils/CommonUtil.java
Implemented a new RESTServiceMediaTypeHandler to import resources provided through interface URLs. 
Fixed issues with creating endpoints when adding Rest service.
Jira Issues
[REGISTRY-3532](https://wso2.org/jira/browse/REGISTRY-3532)
[REGISTRY-3577](https://wso2.org/jira/browse/REGISTRY-3577)
[REGISTRY-3579](https://wso2.org/jira/browse/REGISTRY-3579)
> REGISTRY-3532, 3577, 3579 Improving Rest Service handling capability in Governance Center

- components/registry/org.wso2.carbon.registry.extensions/src/main/java/org/wso2/carbon/registry/extensions/handlers/DeleteHierarchyHandler.java
- components/registry/org.wso2.carbon.registry.extensions/src/test/java/org/wso2/carbon/registry/extensions/test/jdbc/DefaultLifecycleTest.java
- components/registry/org.wso2.carbon.registry.extensions/src/test/java/org/wso2/carbon/registry/extensions/test/utils/BaseTestCase.java
- components/registry/org.wso2.carbon.registry.social.impl/src/test/java/org/wso2/carbon/registry/social/impl/test/activity/BaseTestCase.java
Reverts wso2/carbon-registry#193 -downgrading the kernel version
> Revert "Fix test failures"

- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/indexer/IndexDocumentCreator.java
indexing taxonomy with lowercase values
> indexing taxonomy with lowercase values

- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/AsyncIndexer.java
- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/IndexingManager.java
- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/RegistryConfigLoader.java
This fix is related to the following [1] red mine feature. [Enabling G-Reg/APIM Publisher and Store in separate cluster domains]
[1] - https://redmine.wso2.com/issues/4308
> REGISTRY-3035 Fix

- components/registry/org.wso2.carbon.registry.extensions/src/main/java/org/wso2/carbon/registry/extensions/handlers/utils/EndpointUtils.java
Fixing https://wso2.org/jira/browse/REGISTRY-3783
> Attaching the default lc for endpoints created indirectly

- components/registry/org.wso2.carbon.registry.common/src/main/java/org/wso2/carbon/registry/common/utils/RegistryUtil.java
- components/registry/org.wso2.carbon.registry.search.ui/src/main/resources/web/search/advancedSearch.jsp
Resolve #SECURITYINTERNAL-179 - Fixed identified cross site scripting vulnerabilities
> SECURITYINTERNAL-179 - Fix cross site scripting vulnerabilities

- features/registry-core/org.wso2.carbon.registry.core.server.feature/pom.xml
- pom.xml
Reverts wso2/carbon-registry#227
> Revert "Add http client bundle"

- components/registry/org.wso2.carbon.registry.common/src/main/java/org/wso2/carbon/registry/common/utils/RegistryUtil.java
- components/registry/org.wso2.carbon.registry.search.ui/src/main/resources/web/search/advancedSearch.jsp
Fix validation when obtaining parameter from request
> Fix failing to add RXT

- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/add_collection_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/add_remotelink_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/add_role_permission_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/add_symlink_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/add_text_resource_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/add_user_permission_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/change_role_permissions_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/change_user_permissions_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/controller_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/copy_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/create_version_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/delete_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/delete_version_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/display_text_content_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/edit_text_content_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/import_resource_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/move_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/resource_sub_tree_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/restore_version_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/set_description_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/update_mediatype_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/update_text_content_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/upload_content_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/versions_ajaxprocessor.jsp
This PR fixes XSS vulnerabilities found in the `org.wso2.carbon.registry.resource.ui` module.
> Fix XSS vulnerabilities in the org.wso2.carbon.registry.resource.ui

- components/registry/org.wso2.carbon.registry.common/src/test/java/org/wso2/carbon/registry/common/ResourceDataTest.java
- components/registry/org.wso2.carbon.registry.common/src/test/java/org/wso2/carbon/registry/common/TermDataTest.java
- components/registry/org.wso2.carbon.registry.common/src/test/java/org/wso2/carbon/registry/common/WebResourcePathTest.java
- components/registry/org.wso2.carbon.registry.common/src/test/java/org/wso2/carbon/registry/common/beans/CommentBeanTest.java
- components/registry/org.wso2.carbon.registry.common/src/test/java/org/wso2/carbon/registry/common/beans/RatingBeanTest.java
- components/registry/org.wso2.carbon.registry.common/src/test/java/org/wso2/carbon/registry/common/beans/ReportConfigurationBeanTest.java
- components/registry/org.wso2.carbon.registry.common/src/test/java/org/wso2/carbon/registry/common/beans/SubscriptionBeanTest.java
- components/registry/org.wso2.carbon.registry.common/src/test/java/org/wso2/carbon/registry/common/beans/utils/CommentTest.java
- components/registry/org.wso2.carbon.registry.common/src/test/java/org/wso2/carbon/registry/common/beans/utils/EventTypeTest.java
- components/registry/org.wso2.carbon.registry.common/src/test/java/org/wso2/carbon/registry/common/beans/utils/SubscriptionInstanceTest.java
- components/registry/org.wso2.carbon.registry.common/src/test/java/org/wso2/carbon/registry/common/beans/utils/TagTest.java
- components/registry/org.wso2.carbon.registry.common/src/test/java/org/wso2/carbon/registry/common/eventing/RegistryEventTest.java
- components/registry/org.wso2.carbon.registry.common/src/test/java/org/wso2/carbon/registry/common/utils/CommonUtilTest.java
- components/registry/org.wso2.carbon.registry.common/src/test/java/org/wso2/carbon/registry/common/utils/RegistryUtilTest.java
- components/registry/org.wso2.carbon.registry.common/src/test/java/org/wso2/carbon/registry/common/utils/UserUtilTest.java
- components/registry/org.wso2.carbon.registry.common/src/test/java/org/wso2/carbon/registry/common/utils/artifact/manager/ArtifactManagerTest.java
- components/registry/org.wso2.carbon.registry.event.ws/pom.xml
- components/registry/org.wso2.carbon.registry.extensions/pom.xml
- components/registry/org.wso2.carbon.registry.social.impl/pom.xml
- pom.xml
Add unit tests for registry commons component
Improve unit coverage of registry commons component
>  Add unit tests for registry commons component

- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/utils/RxtUnboundedDataLoadUtils.java
> Fix the indexing issue in unbounded rxt fields 
> Resolves: #254 
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type “Sent” when you have provided new/updated …
> Fix unbounded fields indexing issue

- components/registry/org.wso2.carbon.registry.common/src/test/java/org/wso2/carbon/registry/common/beans/ReportConfigurationBeanTest.java
- components/registry/org.wso2.carbon.registry.resource/src/main/java/org/wso2/carbon/registry/resource/services/utils/CopyResourceUtil.java
- components/registry/org.wso2.carbon.registry.resource/src/test/java/org/wso2/carbon/registry/resource/services/utils/AddCollectionUtilTest.java
- components/registry/org.wso2.carbon.registry.resource/src/test/java/org/wso2/carbon/registry/resource/services/utils/AddResourceUtilTest.java
- components/registry/org.wso2.carbon.registry.resource/src/test/java/org/wso2/carbon/registry/resource/services/utils/CopyResourceUtilTest.java
- components/registry/org.wso2.carbon.registry.resource/src/test/java/org/wso2/carbon/registry/resource/services/utils/DescriptionUtilTest.java
- components/registry/org.wso2.carbon.registry.resource/src/test/java/org/wso2/carbon/registry/resource/services/utils/GetPropertyUtilTest.java
- components/registry/org.wso2.carbon.registry.resource/src/test/java/org/wso2/carbon/registry/resource/services/utils/ImportResourceUtilTest.java
- components/registry/org.wso2.carbon.registry.resource/src/test/java/org/wso2/carbon/registry/resource/services/utils/MoveResourceUtilTest.java
Improve unit test coverage of Registry Resource
Improve unit test coverage of the Registry components
>  Improve unit test coverage of Registry Resource

- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/ResourceSubmitter.java
- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/internal/IndexingServiceComponent.java
Fixes https://github.com/wso2/carbon-registry/issues/258
@daneshk
> Fix growth of initializedTenants list

- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/solr/SolrClient.java
Resolves #262
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …
> Fix solr indexing failure when parsing property values fail.

- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/utils/RxtUnboundedDataLoadUtils.java
> Improve xml parsing logic of RxtUnboundedDataLoadUtils.java
> Link to the PR for changes to the training content in …
> Improve xml parsing logic

- pom.xml
> Addresses issue https://github.com/wso2/carbon-registry/issues/270
> Upgrading httpclient version in carbon-registry
> Upgrade httpclient version

- components/registry/org.wso2.carbon.registry.rest.api/pom.xml
> Upgrade spring-web version

- components/registry/org.wso2.carbon.registry.indexing/pom.xml
- features/content-search/org.wso2.carbon.registry.contentsearch.server.feature/pom.xml
- pom.xml
Update zookeeper version to the original since in apache-zookeeper_3.4.9.wso2v1 bundle there are
no import packages have been used.
> Brief description of the new feature or bug fix as it will appear in the release …
> Update zookeeper version

- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/resource_tree_ajaxprocessor.jsp
This PR adds an html encoding for displayPath attribute value in resource_tree_ajaxprocessor.jsp.
> Link to the PR for changes to …
> Add html encoding for displayPath attribute value in resource_tree_ajaxprocessor.jsp

- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/custom_add_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/resource.jsp
This fixes the issue of not encoding the 'mediaType' parameter in /carbon/resources/custom_add_ajaxprocessor.jsp and 'path' parameter in /carbon/resources/resource.jsp
> Brief description of the new feature or bug …
> Fix Cross-Site Scripting issue

- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/custom_add_ajaxprocessor.jsp
> Add missing imports.
> User should be able to access registry from UI 
> JDK8
> Fix wso2/product-ei/issues/2193

- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/resource_tree_ajaxprocessor.jsp
Reverting encoding changes
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
> Reverting encoding changes

- components/registry/org.wso2.carbon.registry.extensions/src/main/java/org/wso2/carbon/registry/extensions/handlers/ZipWSDLMediaTypeHandler.java
Improvements are done to the archival uploading process
> Improving archival uploading process

- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/resource_tree_ajaxprocessor.jsp
Adding javascript encoding
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
> Adding javascript encoding

- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/solr/SolrClient.java
If user is null, set the anonymous user
> Link to the PR for changes to the training content in …
> Add fix for NPE

- components/registry/org.wso2.carbon.registry.indexing.ui/pom.xml
- components/registry/org.wso2.carbon.registry.indexing/pom.xml
- pom.xml
Upgrade solr and lucene to 5.5.5
Upgrade zookeeper to 3.4.13
> Upgrade Solr and Lucene version to 5.5.5

- components/registry/org.wso2.carbon.registry.activities/pom.xml
- components/registry/org.wso2.carbon.registry.cmis/pom.xml
- components/registry/org.wso2.carbon.registry.extensions/pom.xml
- components/registry/org.wso2.carbon.registry.handler/pom.xml
- components/registry/org.wso2.carbon.registry.indexing/pom.xml
- components/registry/org.wso2.carbon.registry.info/pom.xml
- components/registry/org.wso2.carbon.registry.jcr/pom.xml
- components/registry/org.wso2.carbon.registry.profiles/pom.xml
- components/registry/org.wso2.carbon.registry.properties/pom.xml
- components/registry/org.wso2.carbon.registry.relations/pom.xml
- components/registry/org.wso2.carbon.registry.reporting/pom.xml
- components/registry/org.wso2.carbon.registry.resource/pom.xml
- components/registry/org.wso2.carbon.registry.search/pom.xml
- components/registry/org.wso2.carbon.registry.ws.api/pom.xml
- components/registry/org.wso2.carbon.registry.ws.client/pom.xml
- pom.xml
> Fix integration test failures

- components/registry/org.wso2.carbon.registry.handler/src/test/resources/log4j.properties
- pom.xml
Update the below versions.
- securevault
- axis2
- axiom
- rampart
- commons
- identity.framework
Fix the unit test failure due to debug enabled in CommonUtil class.
> Upgrade axis, axiom versions and fix unit test failures.

- components/registry/org.wso2.carbon.registry.indexing/src/test/resources/log4j.properties
> Fix unit test failure in IndexingHandler.
> Fix unit test failure in IndexingHandler

- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/utils/RxtUnboundedDataLoadUtils.java
fixing https://github.com/wso2/product-apim/issues/5223
> set isMultiValueField as public static

- components/registry/org.wso2.carbon.registry.event.core/src/main/java/org/wso2/carbon/registry/event/core/internal/builder/EventBrokerBuilderDS.java
> change component naming

- components/registry/org.wso2.carbon.registry.indexing/src/main/resources/solr.xml
- components/registry/org.wso2.carbon.registry.indexing/src/test/resources/solr.xml
- features/content-search/org.wso2.carbon.registry.contentsearch.server.feature/src/main/resources/solr/solr.xml
- pom.xml
> Disable Solr logging

- components/registry/org.wso2.carbon.registry.activities/pom.xml
- components/registry/org.wso2.carbon.registry.caching.invalidator/pom.xml
- components/registry/org.wso2.carbon.registry.deployment.synchronizer/pom.xml
- components/registry/org.wso2.carbon.registry.event.core/pom.xml
- components/registry/org.wso2.carbon.registry.event.ws/pom.xml
- components/registry/org.wso2.carbon.registry.eventing/pom.xml
- components/registry/org.wso2.carbon.registry.extensions/pom.xml
- components/registry/org.wso2.carbon.registry.handler/pom.xml
- components/registry/org.wso2.carbon.registry.indexing/pom.xml
- components/registry/org.wso2.carbon.registry.info/pom.xml
- components/registry/org.wso2.carbon.registry.profiles/pom.xml
- components/registry/org.wso2.carbon.registry.properties/pom.xml
- components/registry/org.wso2.carbon.registry.relations/pom.xml
- components/registry/org.wso2.carbon.registry.reporting/pom.xml
- components/registry/org.wso2.carbon.registry.resource/pom.xml
- components/registry/org.wso2.carbon.registry.search/pom.xml
- components/registry/org.wso2.carbon.registry.security/pom.xml
- components/registry/org.wso2.carbon.registry.servlet/pom.xml
- components/registry/org.wso2.carbon.registry.social.impl/pom.xml
- components/registry/org.wso2.carbon.registry.task/pom.xml
- components/registry/org.wso2.carbon.registry.uddi/pom.xml
- components/registry/org.wso2.carbon.registry.webdav/pom.xml
- components/registry/org.wso2.carbon.registry.ws.api/pom.xml
- components/registry/org.wso2.carbon.registry.ws.client/pom.xml
- features/registry-core/org.wso2.carbon.registry.core.ui.feature/pom.xml
- features/registry-core/org.wso2.carbon.registry.search.ui.feature/pom.xml
- features/registry-core/org.wso2.carbon.registry.ui.menu.feature/pom.xml
- features/registry-core/org.wso2.carbon.registry.ui.menu.governance.feature/pom.xml
- pom.xml
add osgi.service.component.version
> add osgi.service.component.version

- features/registry-core/org.wso2.carbon.registry.core.common.feature/pom.xml
- features/registry-core/org.wso2.carbon.registry.core.feature/pom.xml
- features/registry-core/org.wso2.carbon.registry.core.server.feature/pom.xml
> Update kernel feature version
> Update kernel feature version

- components/registry/org.wso2.carbon.registry.activities/pom.xml
- components/registry/org.wso2.carbon.registry.cmis/pom.xml
- components/registry/org.wso2.carbon.registry.extensions/pom.xml
- components/registry/org.wso2.carbon.registry.extensions/src/main/java/org/wso2/carbon/registry/extensions/handlers/EndpointMediaTypeHandler.java
- components/registry/org.wso2.carbon.registry.extensions/src/main/java/org/wso2/carbon/registry/extensions/handlers/XSDMediaTypeHandler.java
- components/registry/org.wso2.carbon.registry.extensions/src/main/java/org/wso2/carbon/registry/extensions/internal/RegistryResourcePermissionsServiceComponent.java
- components/registry/org.wso2.carbon.registry.handler/pom.xml
- components/registry/org.wso2.carbon.registry.indexing/pom.xml
- components/registry/org.wso2.carbon.registry.info/pom.xml
- components/registry/org.wso2.carbon.registry.jcr/pom.xml
- components/registry/org.wso2.carbon.registry.profiles/pom.xml
- components/registry/org.wso2.carbon.registry.properties/pom.xml
- components/registry/org.wso2.carbon.registry.relations/pom.xml
- components/registry/org.wso2.carbon.registry.resource/pom.xml
- components/registry/org.wso2.carbon.registry.search/pom.xml
- pom.xml
> Remove identity framework dependency
> Remove identity framework dependency

- components/registry/org.wso2.carbon.registry.handler/pom.xml
- pom.xml
> Add pax logging service as test dependency
> Add pax logging service as test dependency

- pom.xml
> This PR will update the dependency versions according to the kernel upgrade.
> Update kernel dependencies

- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/retrieve_permission_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/standard_view_ajaxprocessor.jsp
This PR contains changes to fix the issue reported in https://github.com/wso2/product-apim/issues/5657
> Add fix for timeout issue when browsing registry resources

- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/solr/SolrClient.java
Adding debug log for the solr indexing object.
> Added debug log for the solr indexing object.

- components/registry/org.wso2.carbon.registry.jcr/src/main/java/org/wso2/carbon/registry/jcr/retention/RegistryRetentionManager.java
- pom.xml
> Update versions for release

- components/registry/org.wso2.carbon.registry.extensions/pom.xml
- components/registry/org.wso2.carbon.registry.jcr/src/main/java/org/wso2/carbon/registry/jcr/retention/RegistryRetentionManager.java
- pom.xml
Add xalan latest dependency to avoid test failures due to kernel upgrade
> Add xalan latest dependency

- components/registry/org.wso2.carbon.registry.jcr/src/main/java/org/wso2/carbon/registry/jcr/retention/RegistryRetentionManager.java
> Remove unwanted dependencies

- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/solr/SolrClient.java
Fixes https://github.com/wso2/product-apim/issues/6734
> Fix github 6734

- components/registry/org.wso2.carbon.registry.indexing/pom.xml
This PR fixes the jenkins build failure in indexing test cases.
```
Stacktrace
java.lang.NullPointerException: null
at org.wso2.carbon.registry.core.ResourcePath.<init>(ResourcePath.java:47)
at org.wso2.carbon.registry.core.jdbc.handlers.RequestContext.getResourcePath(RequestContext.java:246)
at org.wso2.carbon.registry.indexing.IndexingHandler.put(IndexingHandler.java:71)
at org.wso2.carbon.registry.indexing.IndexingHandlerTest.testPutCollection(IndexingHandlerTest.java:176)  
```
This fails due to a debug level log executed from a test case. This PR enables only info level logs during build time. 
> Brief description of the new feature …
> Fix indexing test failure.

- components/registry/org.wso2.carbon.registry.search.ui/src/main/resources/web/search/advancedSearchForm-ajaxprocessor.jsp
This PR fixes the issue of encoding the propertyName request parameter. 
> Link to the PR for changes to the training content in …
> fix property name parameter encoding

- pom.xml
> Upgrade carbon kernel version range

- features/registry-core/org.wso2.carbon.registry.core.common.feature/pom.xml
- features/registry-core/org.wso2.carbon.registry.core.feature/pom.xml
- features/registry-core/org.wso2.carbon.registry.core.server.feature/pom.xml
- features/registry-core/org.wso2.carbon.registry.core.ui.feature/pom.xml
- features/registry-core/org.wso2.carbon.registry.search.ui.feature/pom.xml
> Change compatible carbon.core.server feature version range

- features/registry-core/org.wso2.carbon.registry.ui.menu.feature/pom.xml
- features/registry-core/org.wso2.carbon.registry.ui.menu.governance.feature/pom.xml
> Change compatible carbon kernel feature version range

- components/registry/org.wso2.carbon.registry.info.ui/src/main/resources/web/info/comment-ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.info.ui/src/main/resources/web/info/comment.jsp
> Encoded the comment in registry resource tap
> Encoded the comment

- components/registry/org.wso2.carbon.registry.extensions/src/main/java/org/wso2/carbon/registry/extensions/handlers/utils/WSDLUtils.java
> Add secured XML Parser in WSDLUtils.java
Related PR https://github.com/wso2/carbon-registry/pull/190
> Add secured XML Parser

- components/registry/org.wso2.carbon.registry.relations.ui/src/main/resources/web/relations/assoTree-ajaxprocessor.jsp
> This PR will do a minor UI fix on the associationType field.
> minor UI fix

- components/registry/org.wso2.carbon.registry.extensions.ui/src/main/java/org/wso2/carbon/registry/extensions/ui/clients/ResourceServiceClient.java
This PR improves extension deletion logic
> Improve Extension deletion logic

- components/registry/org.wso2.carbon.registry.admin.api/src/main/java/org/wso2/carbon/registry/admin/api/resource/IResourceService.java
- components/registry/org.wso2.carbon.registry.resource/src/main/java/org/wso2/carbon/registry/resource/services/ResourceService.java
- components/registry/org.wso2.carbon.registry.resource/src/main/java/org/wso2/carbon/registry/resource/services/utils/GetPropertyUtil.java
- service-stubs/registry/org.wso2.carbon.registry.extensions.stub/src/main/resources/ResourceAdminService.wsdl
- service-stubs/registry/org.wso2.carbon.registry.resource.stub/src/main/resources/ResourceAdminService.wsdl
Implement the operation "getProperties" to get all the properties related to a registry resource given the registry resource path.
> Add getProperties operation to the ResourceAdminServiceStub

- components/registry/org.wso2.carbon.registry.resource/src/main/java/org/wso2/carbon/registry/resource/beans/PropertiesBean.java
- components/registry/org.wso2.carbon.registry.resource/src/main/java/org/wso2/carbon/registry/resource/beans/Property.java
Add Property and PropertiesBean classes to avoid compilation failures.
> Fix compilation error

- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/resource_tree_ajaxprocessor.jsp
This PR adds javascript encoding to required parameters
> Encode for javascript on load sub tree and pick path

- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/resource_tree_ajaxprocessor.jsp
> Introduce Encoding fix

- pom.xml
Reverts wso2/carbon-registry#369
> Revert "Update httpclient version"

- components/registry/org.wso2.carbon.registry.rest.api/pom.xml
- components/registry/org.wso2.carbon.registry.webdav/pom.xml
- pom.xml
Releated issues https://github.com/wso2/product-is/issues/12485
> Dependency version update
- zookeeper 3.4.13 -> 3.4.14
- codehaus.jackson 1.9.2 -> 1.9.13
Change nexus urls from http to https
> Update zookeeper version.

- pom.xml
> Update http components

- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/solr/SolrClient.java
- components/registry/org.wso2.carbon.registry.indexing/src/main/resources/schema.xml
- components/registry/org.wso2.carbon.registry.indexing/src/main/resources/solrconfig.xml
- features/content-search/org.wso2.carbon.registry.contentsearch.server.feature/src/main/resources/solr/registry-indexing/conf/schema.xml
- features/content-search/org.wso2.carbon.registry.contentsearch.server.feature/src/main/resources/solr/registry-indexing/conf/solrconfig.xml
- pom.xml
- Fixes https://github.com/wso2/product-apim/issues/12205
> Upgrading solr and lucene

- components/registry/org.wso2.carbon.registry.rest.api/pom.xml
- components/registry/org.wso2.carbon.registry.webdav/pom.xml
- pom.xml
> Add update fixes to 4.7.x

- features/content-search/org.wso2.carbon.registry.contentsearch.server.feature/pom.xml
- pom.xml
> Upgrading zookeeper bundle

- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/solr/SolrClient.java
- components/registry/org.wso2.carbon.registry.indexing/src/main/resources/schema.xml
- components/registry/org.wso2.carbon.registry.indexing/src/main/resources/solrconfig.xml
- features/content-search/org.wso2.carbon.registry.contentsearch.server.feature/src/main/resources/solr/registry-indexing/conf/schema.xml
- features/content-search/org.wso2.carbon.registry.contentsearch.server.feature/src/main/resources/solr/registry-indexing/conf/solrconfig.xml
- pom.xml
Upgrade to the log4j1 vulnerability fixed solar version
> solr upgrade

- components/registry/org.wso2.carbon.registry.search.ui/src/main/resources/web/search/advancedSearch-ajaxprocessor.jsp
> Encode the sortBy, sortOrder parameters used in Registry advanced search

- features/content-search/org.wso2.carbon.registry.contentsearch.server.feature/pom.xml
- pom.xml
- Remove zookeepr being bundled through carbon-registry as it is embeded in solr 8.11.1.wso2v3 itself
> Remove zookeeper

- pom.xml
As a part of https://github.com/wso2/product-is/issues/12936
> Link to the PR for changes to the training content in …
> Upgrade solr version

- components/registry/org.wso2.carbon.registry.profiles.ui/src/main/resources/web/userprofiles/profiles_add_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.profiles.ui/src/main/resources/web/userprofiles/profiles_edit_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.profiles.ui/src/main/resources/web/userprofiles/profiles_edit_handler_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.profiles.ui/src/main/resources/web/userprofiles/profiles_handler_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.profiles.ui/src/main/resources/web/userprofiles/profiles_main_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.profiles.ui/src/main/resources/web/userprofiles/profiles_select_ajaxprocessor.jsp
> Properly encode request.getParameter method calls in registry profiles ui component
> Encode request parameters in registry profiles UI.

- pom.xml
> Subject
Relates to https://github.com/wso2/product-is/issues/14289
> Update solr version to 8.11.1.wso2v5

- pom.xml
> $Subject
Relates to https://github.com/wso2/product-is/issues/14585
> Update solr version to 8.11.1.wso2v6

- pom.xml
Bump solr dependency `8.11.1.wso2v6` -> `8.11.1.wso2v7`
> Bump solr dependency

- pom.xml
- Update the versions of the dependencies.
- Excluding unused dependencies.
- kernel latest release [1]
- commons-collection latest release [2]
[1] https://github.com/wso2/carbon-kernel/tree/v4.9.0-m3
[2] https://mvnrepository.com/artifact/commons-collections/commons-collections/3.2.2
> Update dependencies in carbon-registry

- features/content-search/org.wso2.carbon.registry.contentsearch.feature/pom.xml
> Remove org.wso2.carbon.registry.core.ui dependency

- pom.xml
$Subject
Prerequisite
- https://github.com/wso2-extensions/identity-local-auth-fido/pull/103
> Upgrade Guava version to 32.1.1.jre

- pom.xml
> Please refer the $subject
- https://github.com/wso2/orbit/pull/1023
> Upgarde solr version to 8.11.1.wso2v9

- pom.xml
Upgrades the solr version to 8.11.1.wso2v11.
- https://github.com/wso2/orbit/pull/1031
- https://github.com/wso2/orbit/pull/1047
> Upgrade the solr version to 8.11.1.wso2v11

- components/registry/org.wso2.carbon.registry.extensions.ui/src/main/resources/web/extensions/deleteExtension-ajaxprocessor.jsp
Fix issues in Delete Extensions
- restricts the service via only HTTP POST.
- Show a generic error msg when an error occurs.
> …
> Fix issues in Delete Extensions

- pom.xml
> Upgrade guava to 33.0

- pom.xml
Upgrade google.guava.failureaccess version to 1.0.2
> Upgrade failure access version to 1.0.2

- components/registry/org.wso2.carbon.registry.resource.ui/src/main/java/org/wso2/carbon/registry/resource/ui/processors/RenameResourceProcessor.java
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/js/resource_util.js
> Sanitize content to prevent security vulnerabilities

- components/registry/org.wso2.carbon.registry.search.ui/src/main/resources/web/search/advancedSearch.jsp
$Subject from sec PR [1]
[1] https://github.com/wso2-support/carbon-registry/pull/438
> Link to the PR for changes to the …
> Add UI permissions

- pom.xml
> Bump carbon parent version to 1.3

- components/registry/org.wso2.carbon.registry.admin.api/pom.xml
- components/registry/org.wso2.carbon.registry.social.api/pom.xml
- components/registry/org.wso2.carbon.registry.ws.api/pom.xml
- pom.xml
> Fix test failure on jDK 11

- components/registry/org.wso2.carbon.registry.admin.api/pom.xml
- components/registry/org.wso2.carbon.registry.social.api/pom.xml
- components/registry/org.wso2.carbon.registry.ws.api/pom.xml
- pom.xml
Disable doc lint due to failures in Java 11
> Disable doc lint due to failures in Java 11

- components/registry/org.wso2.carbon.registry.webdav/pom.xml
- pom.xml
> Bump solr version to 9.5.0.wso2v3

- features/registry-core/org.wso2.carbon.registry.core.feature/pom.xml
> remove search

- pom.xml
Upgraded embedded zookeeper version of solr to 3.9.2
> Bump solr version to 9.5.0.wso2v5

- .github/workflows/coverage.yml
Added git workflow to build the repository and upload code coverage statistics.
> Add coverage.yml workflow file

- pom.xml
> Upgrade solr version 9.5.0.wso2v6

- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/service/ContentBasedSearchService.java
- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/solr/SolrClient.java
This PR fixes the query for retrieving API products by correctly adding the user roles
Fixes https://github.com/wso2/api-manager/issues/2821
> Fix tenant API product disappearance issue after setting DevPortal visibility by roles in Publisher Portal

- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/resource.jsp
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/tree_view_ajaxprocessor.jsp
- This PR encodes the value of the path and treeNavigationPath variables by first using Encode.forHtml to ensure any HTML special characters are safely escaped, followed by Encode.forJavaScriptBlock to protect against JavaScript injection, providing security for both URL and JavaScript contexts.
> Brief description of the new feature or bug fix as it will appear in the …
> Encode path and treeNavigationPath variables with OWASP Java Encoder

- pom.xml
> Upgrade commons-io version to 2.17.0

- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/service/ContentBasedSearchService.java
- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/solr/SolrClient.java
> Currently search with only one registry property. With this PR, added the capability to pass filter queries to the solr search query
> Improve solr client

- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/service/ContentBasedSearchService.java
- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/solr/SolrClient.java
Reverts wso2/carbon-registry#439
> Revert "Fix tenant API product disappearance issue after setting DevPortal visibility by roles in Publisher Portal"

- components/registry/org.wso2.carbon.registry.extensions.ui/src/main/java/org/wso2/carbon/registry/extensions/ui/AddExtensionProcessor.java
- components/registry/org.wso2.carbon.registry.profiles.ui/src/main/resources/web/userprofiles/profiles_handler_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/java/org/wso2/carbon/registry/resource/ui/processors/AddResourceProcessor.java
- components/registry/org.wso2.carbon.registry.social.impl/src/test/java/org/wso2/carbon/registry/social/impl/test/people/userprofile/ClaimTestUtil.java
- pom.xml
Reverts wso2/carbon-registry#437
> Revert "Resolve absolute path for admin console."

- pom.xml
Upgrade the commons-beanutils version from 1.9.4 to 1.11.0.
> Upgrade commons-beanutils version

- components/registry/org.wso2.carbon.registry.resource/src/test/java/org/wso2/carbon/registry/resource/services/utils/GetTextContentUtilTest.java
- components/registry/org.wso2.carbon.registry.resource/src/test/java/org/wso2/carbon/registry/resource/services/utils/GetTextContentUtilWithEncodingTest.java
- components/registry/org.wso2.carbon.registry.resource/src/test/java/org/wso2/carbon/registry/resource/services/utils/ImportResourceUtilTest.java
This PR replaces the invalid URLs with google URLs in the unit tests.
> Update invalid URLs in unit tests

- components/registry/org.wso2.carbon.registry.social.impl/pom.xml
> Add commons dbcp to social impl

- pom.xml
> Downgrade kernel version

- components/registry/org.wso2.carbon.registry.extensions.ui/src/main/java/org/wso2/carbon/registry/extensions/ui/AddExtensionProcessor.java
- components/registry/org.wso2.carbon.registry.profiles.ui/src/main/resources/web/userprofiles/profiles_handler_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/java/org/wso2/carbon/registry/resource/ui/processors/AddResourceProcessor.java
- components/registry/org.wso2.carbon.registry.social.impl/src/test/java/org/wso2/carbon/registry/social/impl/test/people/userprofile/ClaimTestUtil.java
Fixes https://github.com/wso2/api-manager/issues/3743
Related carbon-kernel PR : https://github.com/wso2/carbon-kernel/pull/4371 …
> Resolve absolute path for admin console

- components/registry/org.wso2.carbon.registry.extensions.ui/src/main/java/org/wso2/carbon/registry/extensions/ui/AddExtensionProcessor.java
- components/registry/org.wso2.carbon.registry.profiles.ui/src/main/resources/web/userprofiles/profiles_handler_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/java/org/wso2/carbon/registry/resource/ui/processors/AddResourceProcessor.java
- components/registry/org.wso2.carbon.registry.social.impl/src/test/java/org/wso2/carbon/registry/social/impl/test/people/userprofile/ClaimTestUtil.java
Reverts wso2/carbon-registry#458
> Revert "Resolve absolute path for admin console"
