wso2/carbon-registry

- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/IndexingConstants.java
- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/IndexingManager.java
- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/RegistryConfigLoader.java
These code changes are to restrict a carbon product from running indexing processes if needed.
* By adding \<startIndexing\>false\</startIndexing\> element inside \<indexingConfiguration\> user will be able to stop indexing processes from running.
* If this config element is not present in the registry.xml, carbon server will by default start indexing threads.
> adding registry.xml config to start and stop indexing processes

- components/registry/org.wso2.carbon.registry.rest.api/pom.xml
- components/registry/org.wso2.carbon.registry.rest.api/src/main/java/org/wso2/carbon/registry/rest/api/Artifact.java
- components/registry/org.wso2.carbon.registry.rest.api/src/main/java/org/wso2/carbon/registry/rest/api/Association.java
- components/registry/org.wso2.carbon.registry.rest.api/src/main/java/org/wso2/carbon/registry/rest/api/Associations.java
- components/registry/org.wso2.carbon.registry.rest.api/src/main/java/org/wso2/carbon/registry/rest/api/Comment.java
- components/registry/org.wso2.carbon.registry.rest.api/src/main/java/org/wso2/carbon/registry/rest/api/Comments.java
- components/registry/org.wso2.carbon.registry.rest.api/src/main/java/org/wso2/carbon/registry/rest/api/Copy.java
- components/registry/org.wso2.carbon.registry.rest.api/src/main/java/org/wso2/carbon/registry/rest/api/MetaData.java
- components/registry/org.wso2.carbon.registry.rest.api/src/main/java/org/wso2/carbon/registry/rest/api/Move.java
- components/registry/org.wso2.carbon.registry.rest.api/src/main/java/org/wso2/carbon/registry/rest/api/Properties.java
- components/registry/org.wso2.carbon.registry.rest.api/src/main/java/org/wso2/carbon/registry/rest/api/Property.java
- components/registry/org.wso2.carbon.registry.rest.api/src/main/java/org/wso2/carbon/registry/rest/api/Rate.java
- components/registry/org.wso2.carbon.registry.rest.api/src/main/java/org/wso2/carbon/registry/rest/api/Rating.java
- components/registry/org.wso2.carbon.registry.rest.api/src/main/java/org/wso2/carbon/registry/rest/api/Revision.java
- components/registry/org.wso2.carbon.registry.rest.api/src/main/java/org/wso2/carbon/registry/rest/api/Revisions.java
- components/registry/org.wso2.carbon.registry.rest.api/src/main/java/org/wso2/carbon/registry/rest/api/Tag.java
- components/registry/org.wso2.carbon.registry.rest.api/src/main/java/org/wso2/carbon/registry/rest/api/Tags.java
- components/registry/org.wso2.carbon.registry.rest.api/src/main/java/org/wso2/carbon/registry/rest/api/swagger/SwaggerJaxrsConfig.java
- components/registry/org.wso2.carbon.registry.rest.api/src/main/webapp/WEB-INF/beans.xml
After starting the G-Reg server users will be able to navigate to swagger doc of registry REST API by performing an HTTP get on following URL.
https://<server-name>:<https-port>/resource/1.0.0/swagger/api-docs
Ex - https://localhost:9443/resource/1.0.0/swagger/api-docs
This swagger doc can be added to G-Reg as a swagger artifact and use the embedded swagger UI view of G-Reg to view the documentation.
[1] https://wso2.org/jira/browse/REGISTRY-3029
> Swagger doc for G-Reg registry REST API.

- components/registry/org.wso2.carbon.registry.extensions/src/main/java/org/wso2/carbon/registry/extensions/handlers/utils/RESTServiceUtils.java
This PR ensures that the overview_provider field is no longer populated when a Rest service is created by uploading a Swagger.
Addresses the following issue: [REGISTRY-3381](https://wso2.org/jira/browse/REGISTRY-3381)
> Fix for REGISTRY-3381

- components/registry/org.wso2.carbon.registry.extensions/src/main/java/org/wso2/carbon/registry/extensions/handlers/SwaggerMediaTypeHandler.java
- components/registry/org.wso2.carbon.registry.extensions/src/main/java/org/wso2/carbon/registry/extensions/handlers/WADLMediaTypeHandler.java
- components/registry/org.wso2.carbon.registry.extensions/src/main/java/org/wso2/carbon/registry/extensions/handlers/ZipWSDLMediaTypeHandler.java
Functionality needed to provide the capability of adding a property in registry.xml to specify whether to create the service artifact or not is implemented in the media type handlers.
> Fix for REGISTRY-3603

- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/display_text_content_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/edit_text_content_ajaxprocessor.jsp
To disallow registry resource viewer/editor disallowing running harmful client-side js scripts.
This fix encodes the content (to be viewed from HTML) of the resources when reading from registry browser text viewer/editor disallowing running harmful client-side js scripts.
> Encode content in resource text viewer/editor

- components/registry/org.wso2.carbon.registry.indexing/src/test/java/org/wso2/carbon/registry/indexing/solr/SolrClientTest.java
jenkins server build is failing due to pockmocking bytecode validation error. This PR is to temporary disable SolrTest till we fix the testcase. Create issue #266 to track this failure
To make the jenkins build stable again
disable SolrClientTestCase temporary
> Fix jenkin build failure due to bytecode verification fail

- components/registry/org.wso2.carbon.registry.indexing/pom.xml
- features/content-search/org.wso2.carbon.registry.contentsearch.server.feature/pom.xml
- pom.xml
> This repo uses an old apache-zookeeper version. Created issue https://github.com/wso2/carbon-registry/issues/269 to track this.
> To update apache-zookeeper to the latest orbit version
> Update zookeper dependency version

- components/registry/org.wso2.carbon.registry.rest.api/src/main/java/org/wso2/carbon/registry/rest/api/Properties.java
- components/registry/org.wso2.carbon.registry.rest.api/src/main/java/org/wso2/carbon/registry/rest/api/Property.java
> When storing a value with a comma in the registry, when making a GET request to the endpoint "/resource/1.0.0/properties" it returns an array with two values.
Resolves https://github.com/wso2/carbon-registry/issues/272.
> Fixing the rest API for returning the property values.
> Changed the splitting values using comma and now properties are returned as a object array.
> Storing a single value with a comma in the registry.
> N/A
> N/A
> N/A
> N/A
> N/A
N/A
N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> Fix storing a single value with a comma in the registry

- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/solr/SolrClient.java
Solr indexing fails if the property value cannot be parsed to the defined type such as INT, DOUBLE etc. Moreover, long type values are parsed as INT type.
Better to default to string type and support indexing if parsing fails.
Solr indexing fails if the property value cannot be parsed to the defined type such as INT, DOUBLE etc. Moreover, long type values are parsed as INT type.
Better to default to string type and support indexing if parsing fails.
Solr indexing fails if the property value cannot be parsed to the defined type such as INT, DOUBLE etc. Moreover, long type values are parsed as INT type.
Better to default to string type and support indexing if parsing fails.
So if the value is an above-mentioned type and indexing fails, we consider it as string value when indexing the …
> Fix solar indexing failure when parsing property values fail

- components/registry/org.wso2.carbon.registry.admin.api/pom.xml
- pom.xml
>javax.activation is removed from JDK 11. add it as a orbit to work with jdk 11 products
> Add entry to support with JDK 11

- components/registry/org.wso2.carbon.registry.extensions.ui/pom.xml
- components/registry/org.wso2.carbon.registry.extensions/pom.xml
- components/registry/org.wso2.carbon.registry.reporting.ui/pom.xml
- components/registry/org.wso2.carbon.registry.resource.ui/pom.xml
- components/registry/org.wso2.carbon.registry.resource/pom.xml
- components/registry/org.wso2.carbon.registry.social.impl/pom.xml
- components/registry/org.wso2.carbon.registry.ws.api/pom.xml
- components/registry/org.wso2.carbon.registry.ws.client/pom.xml
> Add support for jdk11. javax.activation is removed from jdk 11. manually import it
> Add support for jdk11

- components/registry/org.wso2.carbon.registry.common/pom.xml
- components/registry/org.wso2.carbon.registry.common/src/main/java/org/wso2/carbon/registry/common/utils/RegistryUtil.java
replace manual sanitizing with OWASP encoding.
> carbon-registry-common: use OWASP encoder for HTML-encoding

- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/RegistryConfigLoader.java
- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/solr/SolrClient.java
This PR fixes the error reported in https://github.com/wso2/product-apim/issues/6476
Error `Caused by: org.apache.lucene.search.BooleanQuery$TooManyClauses: maxClauseCount is set to 1024` occurs when the solr query has more than 1024 clauses. 
when a user has many application roles (used for internal APIM functionalities) all these roles are appended to the solr search query and it is possible the clause count becomes greater than 1024 in a situation like this. 
As the solution here we are adding the support for optionally skipping 'Application/*' roles in the search query.
<skipRolesByRegex>Application\/.*</skipRolesByRegex>
> Fix https://github.com/wso2/product-apim/issues/6476

- components/registry/org.wso2.carbon.registry.resource/src/main/java/org/wso2/carbon/registry/resource/services/utils/GetTextContentUtil.java
> avoid exposing java version in the User-Agent header
> set the User-Agent header to an empty string
> remove UA header from import resource request

- components/registry/org.wso2.carbon.registry.cmis/pom.xml
> Remove central repository from CMIS pom file to fetch artifacts from
WSO2 Nexus.
> Remove central repositroy from CMIS pom file.

- components/registry/org.wso2.carbon.registry.info.ui/src/main/resources/web/info/comment-delete-ajaxprocessor.jsp
This PR will fix minor UI issue in delete comments functionality
Front-porting of https://github.com/wso2-support/carbon-registry/pull/299
Encoded the commentString, commentedTime, commentedUser fields using OWASP Java Encoder
carbon-registry 4.6.28 - https://github.com/wso2-support/carbon-registry/pull/301
carbon-registry 4.6.38 - https://github.com/wso2-support/carbon-registry/pull/299
carbon-registry 4.7.13 - https://github.com/wso2-support/carbon-registry/pull/305
carbon-registry 4.7.32 - https://github.com/wso2-support/carbon-registry/pull/303
> Minor UI Fix in Delete Comments Functionality

- components/registry/org.wso2.carbon.registry.resource.ui/src/main/java/org/wso2/carbon/registry/resource/ui/processors/GetResourceTreeProcessor.java
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/raw-collection-content.jsp
This PR will fix a minor UI issue in resource UI
Front-porting of https://github.com/wso2-support/carbon-registry/pull/300
Encoded the resource name related fields using OWASP Java Encoder
carbon-registry 4.6.28 - https://github.com/wso2-support/carbon-registry/pull/302
carbon-registry 4.6.38 - https://github.com/wso2-support/carbon-registry/pull/300
carbon-registry 4.7.13 - https://github.com/wso2-support/carbon-registry/pull/306
carbon-registry 4.7.32 - https://github.com/wso2-support/carbon-registry/pull/304
> Minor UI Fix in Resource UI

- pom.xml
Related Issues: wso2/product-is#12485
> Update commons-io version to 2.7.0.wso2v1
Depends on https://github.com/wso2/carbon-registry/pull/370
> Dependancy version update of commons-io.

- components/registry/org.wso2.carbon.registry.resource/src/test/java/org.wso2.carbon.registry.resource.test/Registry2395Test.java
The previous urls were not available. Therefore the corresponding WSDL and XSD data file urls were taken from Github. The test case is used to read  the content of these types of urls
> Change WSDL and XSD urls for testing

- components/registry/org.wso2.carbon.registry.search.ui/src/main/resources/web/search/advancedSearchForm-ajaxprocessor.jsp
Following request parameters are encoded to fix a reflected XSS vulnerability in advancedSearch.jsp
- mediaType
- rightOp
- leftOp
- rightPropertyValue
- leftPropertyValue
> Fix XSS vulnerability in registry advanced search

- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/solr/EasySSLProtocolSocketFactory.java
The SSL context protocol should be upgraded to a more secure protocol to fix "Selection of Less-Secure Algorithm During Negotiation" security vulnerabilities.
> Upgrade SSL context protocol to TLSv1.2

- components/registry/org.wso2.carbon.registry.indexing/pom.xml
- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/indexer/MSPowerpointIndexer.java
- pom.xml
This PR adds the following changes,
- [Bump commons-io version to 2.15.1.wso2v1](https://github.com/wso2/carbon-registry/commit/4396ce5e09c8d90bf2453c04b1ad8cfe40ec0caf)
- [Bump poi version to 5.2.5.wso2v1](https://github.com/wso2/carbon-registry/commit/d741d8890b0ddb3e31cfc3e4f2b4f2fdcaeb5020)
> Bump the POI version to 5.2.5.wso2v1

- pom.xml
This PR bumps the solr version to 9.5.0.wso2v4.
Fixes https://github.com/wso2/api-manager/issues/2677
> Bump solr version to 9.5.0.wso2v4

- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/content_ajaxprocessor.jsp
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/js/purify.js
- components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/web/resources/js/resource_util.js
Sanitize rich text editor content before rendering in registry ui using domPurify library[1][2].
DomPurify was already used in master branch for react console to Sanitize email template body input before rendering preview[3] 
[1] https://www.npmjs.com/package/dompurify
[2] https://unpkg.com/dompurify@3.0.9/dist/purify.js
[3] https://github.com/wso2/identity-apps/pull/5599
> Sanitize rich text editor content before rendering in registry ui

- components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/indexer/IndexDocumentCreator.java
Currently we cannot override registry propertie data in the indexdocumentcreator (https://github.com/wso2/carbon-registry/blob/master/components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/indexer/IndexDocumentCreator.java#L123) . Whatever fields sent from a custom index document https://github.com/wso2/carbon-registry/blob/master/components/registry/org.wso2.carbon.registry.indexing/src/main/java/org/wso2/carbon/registry/indexing/indexer/IndexDocumentCreator.java#L123 is overridden. This fix stop this overriding part
> Improvement to IndexDocumentCreator

- pom.xml
Bump solr from solr_9.5.0.wso2v7 to solr_9.5.0.wso2v8.
- https://github.com/wso2/orbit/pull/1237
- https://github.com/wso2-support/orbit/pull/449
- https://github.com/wso2/product-is/issues/24905
> [Bump] Solr version to 9.5.0.wso2v8

- pom.xml
Since guava and guava failure access jars are also packed from the carbon-kernel with [1], we need to make sure that the versions are upgrade at both the locations, if not it could cause multiple JAR versions to get packed to the product.
[1] - https://github.com/wso2/carbon-kernel/pull/4339 
Inform developers to bump dependency versions in all the locations. Partially fixes: https://github.com/wso2/product-is/issues/24653.
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
-  Ran FindSecurityBugs plugin and verified report? yes
-  Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> Add comment for guava related dependency versions
